### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by jpochyla** [Sinono3/souvlaki#1]
Hi! I began working on the Mac support and I hope I'll have something to show in a couple of days. I was wondering if there's any specific reason for the `MediaControls` facade in `lib.rs`, in other words why are the platform-specific `MediaControls` structs not exposed directly, avoiding the need for an ext trait? Thanks!

**Comment by Sinono3** [comment]
To be honest, it's my first time making a cross-platform library and I followed the structure that [`winit`](https://github.com/rust-windowing/winit/) uses (thus also the polling system, even though it is not needed). I think the cross-platform `MediaControls` facade is used to provide an abstraction for the user and make it easier to store in structs without having to write `cfg!` every now and then, but that's how I see it, maybe there is a better way. What do you think? Do you think access to the raw platform-specific structs would be better? By the way, thanks for working on improving the library🙂

**Comment by Sinono3** [comment]
Closed with #3.
