### ISSUE TITLE
Polling model

### ISSUE THREAD

**Issue by jpochyla** [Sinono3/souvlaki#2]
Hi! What do you think about switching from the polling model to a callback approach? In my app I don't have any event polling to piggyback at, and passing a `impl Fn(...) + Send + 'static` would work best. Event queue is easily implementable on top, outside of `souvlaki`.

**Comment by Sinono3** [comment]
Hello! Yeah, callbacks would be more flexible I think. The Windows API also works via callbacks, and I just checked and it seems MPRIS in Linux as well. I'll try to make a prototype on the weekend, but if you'd like you can work on it too😄

**Comment by jpochyla** [comment]
Great! I have it almost ready, PR incoming :) I'm afraid I can't test the Windows part though, as I don't have any Windows machine around.

**Comment by Sinono3** [comment]
Closed with #3.
