### ISSUE TITLE
Using the library without `winit::event_loop`

### ISSUE THREAD

**Issue by aome510** [Sinono3/souvlaki#23]
Hi, I'm trying to use this library in **MacOS Monterey 12.3.1**. 

Running `examples/print_events` doesn't work (no media event printed even when I press one, no metadata shown up in the media control). Running `example/example.rs` works perfectly but I'm not sure I understand the requirement of `winit` library here. `winit` and `winit::event_loop` seem to be the only difference between `examples/print_events.rs` and `examples/example.rs`

Does `souvlaki` work without `winit`, as I see that `winit` is only included as the `devdependencies`? Am I missing something here?

**Comment by YXL76** [comment]
Media control is only available for window processes on MacOS.

**Comment by aome510** [comment]
> Maybe it has to do with the thread being blocked. Can you try opening the media controls in another thread and/or reducing the sleep time?

Still not work AFAICT. I guess the reason is because MacOS needs an open window to listen to the events, as other mentioned. 

Will close this issue for now. Thanks.

**Comment by Sinono3** [comment]
I'd appreciate if someone with access to MacOS could pin down the behaviour of media controls and window processes, so it can be stated in the crate's documentation and prevent misunderstandings. I'm going to put a warning in the docs for now.

**Comment by ILikeTeaALot** [comment]
From my experience with a NodeJS library I used with Electron (electron-media-service), it is likely that an application event-loop is required (i.e. Winit's event_loop), but a window itself is not strictly required (as it is common for Mac OS applications to continue running despite no open windows, the event loop would continue anyway)

I think the specific requirement would be a running AppDelegate, regardless of the existence of any windows.
