### ISSUE TITLE
Support for other platforms

### ISSUE THREAD

**Issue by 0323pin** [Sinono3/souvlaki#25]
Hi,

Today I wanted to build [`spotify-player`](https://github.com/aome510/spotify-player) with the [`media-control`](https://github.com/aome510/spotify-player/issues/49) feature enabled on NetBSD. But, I realized that `souvlaki` only supports Windows, Linux and MacOS.

Any chance to add support for other platforms where MPRIS/dbus is supported? I don't really see what could be Linux specific in `src/platforms/linux/mod.rs`. Maybe `unix.rs` would be a possibility? Or, just define `target_os = "netbsd"` and use the same `mod.rs`?

Thanks!

**Comment by Sinono3** [comment]
Closed with #26

**Comment by 0323pin** [comment]
@Sinono3 would it be possible to provide a new release in order to to allow other projects that depend on `souvlaki` to support NetBSD?
Thanks!

**Comment by Sinono3** [comment]
Sure! Just uploaded 0.5.2.

**Comment by 0323pin** [comment]
Thank 👍
