### ISSUE TITLE
Support HWND directly

### ISSUE THREAD

**Issue by ShayBox** [Sinono3/souvlaki#29]
Why do you require a `*mut c_void` then convert it to `HWND` internally, when every windows library directly gives you `HWND`.  
https://github.com/Sinono3/souvlaki/blob/master/src/platform/windows/mod.rs#L53  
How do you even convert `HWND` to `*mut c_void`? None of the examples even show using the library with any windows crate.

**Comment by Sinono3** [comment]
Hi. In the [windows crate, the HWND is just a wrapper around isize](https://docs.rs/windows-sys/latest/windows_sys/Win32/Foundation/type.HWND.html). The HWND is practically an IntPtr, therefore converting `HWND` to `*mut c_void` is just a cast. To convert it see: [Getting a windows-rs HWND from winit?](https://stackoverflow.com/questions/72223205/getting-a-windows-rs-hwnd-from-winit). Not all HWND implementations by different crates are the same. Ex.: in [`winapi`](https://docs.rs/winapi/latest/winapi/shared/windef/type.HWND.html), an empty enum is used. Maybe if we supported HWND directly it would not be HWND but isize.

**Comment by ShayBox** [comment]
Thank you :+1:
