### ISSUE TITLE
[Meta] Git tags and / or a changelog file?

### ISSUE THREAD

**Issue by hasezoey** [Sinono3/souvlaki#45]
I was browsing through to update to `0.7`, but wanted to know the changes but noticed there is no easy way like a `CHANGELOG` file or git tags or github releases, this issue is to ask for them to be added (git tags should be the easiest).

- [x] git tags
- [x] github releases
- [x] changelog file

**Comment by LucasFA** [comment]
In particular I would ask for breaking changes notice. Of course, the answer had to be in PR #42

**Comment by Sinono3** [comment]
Thanks for the suggestion. Definitely needed. Starting from 0.7.1 there will be changelogs and releases.
