### ISSUE TITLE
Album art support

### ISSUE THREAD

**Issue by Sinono3** [Sinono3/souvlaki#6]
This feature is also crucial to souvlaki, especially on Windows, where the album art is displayed on the screen when pressing any media key.

**Comment by jpochyla** [comment]
I'd love this as well, although I'm not sure how to represent the image. URL, or a type from the `image` crate? I'm not sure if any platform natively supports URLs, so maybe just the second one?

**Comment by Sinono3** [comment]
Well, let's see:

- MPRIS specification:

	> ### mpris:artUrl
	>
	> URI: The location of an image representing the track or album. Clients should not assume this will continue to exist when the media player stops giving out the URL.

	From my experience, when the album art is a local file the artUrl is a URI starting with `file://`, leading to the cover image.

- On Windows, updating the `Thumbnail` field of  [SystemMediaTransportControlsDisplayUpdater](https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrolsdisplayupdater.thumbnail?view=winrt-19041#Windows_Media_SystemMediaTransportControlsDisplayUpdater_Thumbnail) is what we're looking for. It seems straightforward, it only needs to be fed a [`RandomAccessStreamReference`](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Storage/Streams/struct.RandomAccessStreamReference.html), which allows for more flexibility than an URI, it can also be created from files or streams.
- I don't know about MacOS though 🥲

I guess we can just take an URI as input, and if the user wants to use an image in memory, allow them to input that and just optimize according to each specific platform. For example: a video player wants to procedurally extract a thumbnail of a video, and then feed it to souvlaki. The input could be just an image from the image crate. 

- Since Windows has support for raw image streams, we would just make a stream to the image data, after doing some sort of conversion.
- On Linux, we could store the data on a `tmpfs`, set `mpris:artUrl` to the path, and delete the file on drop.

If we do have this behaviour, maybe separating it in a feature and warning users would be a good idea, since it could be disruptive.

**Comment by jpochyla** [comment]
Thanks for the research! Good to know that URL is the only way on MPRIS, and in the end it's not so complicated to download it asynchronously in MacOS, either.

**Comment by Sinono3** [comment]
Closed with #8.
